GET http://facebook.com


###

GET https://api.wordnik.com/v4/word.json/slay/definitions?limit=200&includeRelated=false&useCanonical=false&includeTags=false&api_key=ac6099e63826b8650f05e22c4cc08baa2f21668e3f16176fd